---
title: "02-Analyze"
author: "Ian Adams"
date: "3/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)

library(tidyverse)
library(readr)
library(here)
library(skimr)
library(ggplot2)
library(lubridate)
library(dplyr)

library(ggstance)
library(ggalt)
```

## Import

Don't forget to pull from the git before start, so as to get fresh data from WAPO.

```{r remedy001, message=FALSE, warning=FALSE, echo=FALSE}

here::here("WAPO data-police-shootings")

df <- read_rds(here("Data", "Clean", "WAPO_clean.rds"))

df$date <- ymd(df$date)

```

## Armed Status Breakdown 

```{r remedy002}

## Fix "claimed" armed status to "unarmed" and equate "unknown" and "undetermined"
df$armed_bucket <- df$armed_bucket %>%
  fct_recode(
    "unarmed" = "claim",
    "unknown" = "undetermined"
  )

## Recoding df$armed_bucket into df$armed_bucket_rec
df$armed_small <- df$armed_bucket %>%
  fct_recode(
    "armed" = "strange",
    "armed" = "gun like",
    "armed" = "sharp",
    "armed" = "blunt",
    "armed" = "strange object",
    "armed" = "carjack",
    "armed" = "explosive",
    "armed" = "gun",
    "armed" = "vehicle",
    "armed" = "chemical",
    "armed" = "taser"
  )

## Armed Status by Race
p1 <- df %>% 
  na.omit(race_rec) %>%
  ggplot(aes(x = race_rec, fill = armed_small)) +
  geom_bar(position = "stack")

## Armed status by gender

p2 <- df %>% 
  na.omit(gender) %>%
  ggplot(aes(x = gender, fill = armed_small)) +
  geom_bar(position = "stack")

## Shootings over time, by armed and threat status

p3 <- df %>%
 filter(!is.na(armed_bucket)) %>%
 ggplot() +
  aes(x = armed_small, fill = threat) +
  geom_bar(position = "stack") +
  scale_fill_hue(direction = 1) +
  labs(
    y = "Number of Shootings",
    x = NULL,
    title = "Police Fatal Shootings",
    subtitle = "2015-2022, by armed and threat status",
    caption = "Data from Washington Post Police Shootings Database"
  ) +
  hrbrthemes::theme_ipsum_tw()

ggsave(p3, filename = here("Output", "time_armed_threat.jpg"))

```


## Most Common Armed Weapons

```{r remedy003}

temp <- table(df$armed_bucket) / nrow(df) * 100
temp <- sort(temp, decreasing = TRUE)
temp <- round(temp, digits = 2)
temp
```
## Gender Breakdowns

```{r remedy004}
table(df$gender) / nrow(df) * 100

```

## Race Breakdowns

```{r remedy005}

## Percentage by race
temp <- table(df$race_rec) / nrow(df) * 100
temp <- sort(temp)
temp <- round(temp, digits = 2)
temp

## Barplot by race

#Make "NA" into an explicit factor level
df$race_rec <- df$race_rec %>%
  fct_explicit_na("Unknown")

df$race_rec <- factor(df$race_rec,
                         levels = names(sort(table(df$race_rec), 
                                             decreasing = TRUE)))



ggplot(df, aes(x = race_rec)) + 
  geom_bar() 


## Or flipped and with proportion

ggplot(df, aes(x = race_rec)) + 
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  coord_flip() 

```
## Age Breakdowns

```{r remedy006}
## Histogram
ggplot(df, aes(x = age)) + 
  geom_histogram(aes(y = (..count..)/sum(..count..)))

## Density

ggplot(df, aes(x = age)) + 
  geom_density()

## Simple Stat Count

ggplot(df, aes(x = age)) + 
  stat_count(aes(y = (..count..)/sum(..count..)))

```


## Plotting over time

```{time, fig.height=7, fig.width=9}

df$dummy <- 1
df$month_year <- floor_date(df$date, unit = "month")
df$year       <- year(df$date)


monthly_shootings <- df %>%
  group_by(month_year) %>% 
  summarize(dummy = sum(dummy))

#head(monthly_shootings)

## Plot shootings by month
ggplot(monthly_shootings, aes(x = month_year,
                              y = dummy)) +
  geom_line()

## Shootings per month overall
ggplot(data = df, aes(x = month(date, label = TRUE))) + 
        geom_bar(aes(fill = ..count..)) +
        theme_minimal() +
        theme(legend.position = "none") +
        scale_y_continuous(expand=c(0,0)) +
        scale_fill_gradient(low = "royalblue3", high = "navyblue") +
        labs(x = NULL, y = "Number of deaths")

## Plot shootings by year
yearly_shootings <- df %>%
  group_by(year) %>% 
  summarize(dummy = sum(dummy))
ggplot(yearly_shootings, aes(x = year, 
                             y = dummy)) +
  geom_line()
## OR
ggplot(data = df, aes(x = date)) + 
        geom_histogram(aes(fill = ..count..), bins = 25) +
        theme_minimal() +
        theme(legend.position = "none") +
        scale_fill_gradient(low = "royalblue3", high = "navyblue") +
        labs(x = NULL, y = "Number of deaths")


## Weekday analysis

ggplot(data = df, aes(x = wday(date, label = TRUE))) + 
        geom_bar(aes(fill = ..count..)) +
        theme_minimal() +
        theme(legend.position = "none") +
        scale_y_continuous(expand=c(0,0)) +
        scale_fill_gradient(low = "royalblue3", high = "navyblue") +
        labs(x = NULL, y = "Number of deaths")

```


## Top 15 States

```{r, fig.height=9, fig.width=9}
stateinfo <- df %>% group_by(state) %>% summarise(n = n()) %>% 
        arrange(desc(n)) %>% top_n(15) %>% 
        mutate(state = factor(state, levels = rev(unique(state))))

ggplot(stateinfo) +
  aes(x = state, fill = state, weight = n) +
  geom_bar() +
  scale_fill_manual(
    values = c(PA = "#A6CEE3",
    LA = "#3B8ABE",
    NM = "#72B29C",
    MO = "#84C868",
    OH = "#4F9F3B",
    WA = "#EC9A91",
    TN = "#E93E3F",
    OK = "#F06C45",
    NC = "#FDAC4F",
    CO = "#FB820F",
    GA = "#D1AAB7",
    AZ = "#8C66AF",
    FL = "#A99099",
    TX = "#EEDB80",
    CA = "#B15928")
  ) +
  labs(
    y = "Number of deaths",
    title = "Top 15 States for Police Fatal Shootings",
    subtitle = "2015-2022",
    caption = "Washington Post data"
  ) +
  coord_flip() +
  hrbrthemes::theme_ipsum_tw() +
  theme(legend.position = "none")
```


## Armed Status? (top 15 reported categories)

```{r}

df$armed_bucket <- df$armed_bucket %>%
  fct_explicit_na("unknown")

armedinfo <- df %>% group_by(armed_bucket) %>% summarise(n = n()) %>% 
        arrange(desc(n)) %>% top_n(15) %>% 
        mutate(armed = factor(armed_bucket, levels = rev(unique(armed_bucket))))

ggplot(data = armedinfo, aes(x = n, y = armed)) +
  geom_barh(stat = "identity", aes(fill = n)) +
  theme_minimal(base_size = 13) +
  theme(legend.position = "none") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_fill_gradient(low = "royalblue3", high = "navyblue") +
  labs(
    y = NULL,
    x = "Number of deaths",
    title = "Top 15 Suspect Weapon Types in Police Fatal Shootings",
    subtitle = "2015-2022",
    caption = "Washington Post data"
  )

ggsave(filename = here("Output", "top15_suspect-weapon-type.jpg"))

``` 

### Was the Person Killed Fleeing?

```{r}
df$flee_bucket <- df$flee_bucket %>%
  fct_explicit_na("Unknown")

ggplot(data = df, aes(y = flee_bucket)) + 
        geom_barh(aes(fill = ..count..)) +
        theme_minimal(base_size = 13) +
        theme(legend.position = "none") +
        scale_x_continuous(expand=c(0,0)) +
        scale_fill_gradient(low = "royalblue3", high = "navyblue") +
        labs(y = NULL, x = "Number of deaths")
```